### PR TITLE
added intro in the readme

### PR DESCRIPTION
**Pull request by dgmouris**
link to ticket https://github.com/dgmouris/petroltekdav/pull/1

refers to issue https://github.com/dgmouris/petroltekdav/pull/1

### CODE REVIEW

**Comment by komalpreetk700** [comment]
looks good

**Comment by CGlinka95** [comment]
Looks good to me! Nice work

**Comment by shoncur** [comment]
Wowee a pull request

**Comment by abraara** [comment]
nice

**Comment by MandeqBalah** [comment]
Nice!

**Comment by KimJoshua01** [comment]
awesome

**Pull request merged**
